<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gulp</title>

  <!-- styles -->
  <link rel="stylesheet" href="./build/css/main.min.css">

  <!-- js -->
  <script src="./build/js/all.js"></script>
</head>

<body>
  <header>
    <h1>Gulp Config</h1>
  </header>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit cumque placeat ratione cupiditate! Cumque tempora nostrum amet corporis, nobis sint. Quod esse cum animi corrupti. Dolorum molestias aliquam id corporis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi nemo neque eveniet cumque, quaerat pariatur odit quia et possimus nobis laborum est qui optio nihil sapiente, numquam itaque, ipsum beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa incidunt eius non minima fugiat veniam sapiente repellat, possimus nobis? Labore id, ipsa tempore expedita assumenda magni laboriosam sit pariatur cupiditate.</p>
</body>

</html>